image: Elev8-Groundstation/PropIcon.png
type: hardware

links:
        Source Code: https://github.com/parallaxinc/Flight-Controller
        Hardware: https://www.parallax.com/product/80204
        Elev8-V3 Quadcopter: https://www.parallax.com/product/80300
        Calibration and Tuning Guide: http://learn.parallax.com/calibrating-and-performance-tuning-your-elev-8-v3
